[dev]                                          
   framework = "#custom"                                                    
   command = "npm run dev"             
   targetPort = 3000
   debug = true
   port = 8888
   publish = "dist"